### ISSUE TITLE
01 -- I Love My Gramma(r) -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#16]
Tasks
* [X] Create a new Issue with these tasks!
* [x] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x] Begin your wiki **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**{S}
    * [x] Create a new page in your `TIY-Assignments` wiki called _Assignment Evaluation_. Write down your thoughts on the prework. Were the expectations clear? What parts really connected with you? Could any topics have been presented better? Was any of the assignment a review for you? 
    * [x] Create a second page in your `TIY-Assignments` wiki called _Light Bulbs_. Write down things about Ruby and `git` that you understand already.
    * [x] Create a third page in your `TIY-Assignments` wiki called _Things I Don't Get Yet_. Write down current struggles.
* [x] Edit your wiki **(please do these as your final tasks)**
{S}
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. Same guidelines as for the prework, plus: Did the lecture feel connected to the assignment? How long did you spend on the whole thing? How long did you estimate before you started?
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [x] Use the Terminal in your computer to:
{M}
    * [x] create a branch of your `TIY-Assignments` repo which you cloned from GitHub, called `feature/01--I-love-my-gramma(r)`, with `git branch`
    * [x] switch to the branch you just created with `git checkout`
    * [x] Create at least one file and directory as described above in _Deliverables_.
    * [x] Add and commit your work with `git status`, `git add`, and `git commit`
    * [x] Push your commits to Github with `git push`
    * [x] In Github, open a PR _from_ `feature/01--I-love-my-gramma(r)` _into_ `master`
* [x] **Data Types** -- Document what you know about the four data types we've worked with and **commit once for each data type**. I've outlined the format you should use below, using as an example a _special bonus data type_! 
{L}
    * [x] Checkpoint: Created and committed an empty file called `docs/data_types.md`!
    * [x] Checkpoint: Committed documentation of the first data type!
    * [x] Checkpoint: Committed documentation of the second data type!
    * [x] Misson Complete: Commited documentation of all data types!
* [x] **[Try Git](http://try.github.com)**. 
{S}

**Comment by Peterortiz82** [comment]
Wiki Pages
https://github.com/Peterortiz82/TIY-Assignments/wiki

PR Request
https://github.com/Peterortiz82/TIY-Assignments/commit/65d67c2ca80bee6b0168f77fe3e29079329bf019

**Comment by jspencerhopkins** [comment]
:+1:
