### ISSUE TITLE
03 -- Method to the Madness -- Ivan Sherman

### ISSUE THREAD

**Issue by ivansherman** [TheIronYard--Orlando/ROR--2015--SPRING#31]
- [X] A _WIP Issue_ in the class repo "S"
  *  [X] Titled appropriately "S"
  *  [X] With check boxes for the tasks *and any subtasks you can identify* "S"
  *  [X] Estimates for the top-level checkboxes "S"
*    [X] Update your `TIY-Assignments` wiki "M"
*  [X] Create a branch in your `TIY-Assignments` repo, named appropriately "M"
*  [X] include a `code/` folder with files for each of the three (or four) coding challenges you undertake"XL"
*  [X] A Pull Request in your `TIY-Assignments` folder as on previous assignments
*  [ ] Comments on your WIP Issue as on previous assignments "S"

**Comment by ivansherman** [comment]
Link to new Branch under "feature/03--method-to-madness"

https://github.com/ivansherman/TIY-Assignments.git

**Comment by bgates** [comment]
Just add in the comments on your WIP issue and I'll close this.

**Comment by ivansherman** [comment]
I thought what I had just added was a comment. i really do not get the comments parts.
