### ISSUE TITLE
03 -- Method to the Madness-- Joe Cursi

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#32]
* [X] A WIP in the class repo-(S)
    * [X] Titled appropriately-(S)
	* [X] With check boxes for the tasks-(S)
	* [X] any subtasks you can identify-(S)
	* [X] Estimates for the top-level checkboxes-(S)
* [X] Update your `TIY-Assignments` wiki-(S)	
* [] Create a branch in your `TIY-Assignments` repo, named appropriately
	* [X] include a `code/` folder with files for each of the three (or four) coding challenges you undertake
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments	
* [X] Comments on your WIP Issue as on previous assignments

**Comment by malkin28025** [comment]
Tasks

Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
End of lab wiki edit
Add your thoughts on this assignment to the Assignment Evaluation page.
Update Light Bulbs and Things I Don't Get Yet to reflect how you feel at the end of lab.
Use the Terminal in your computer to:
create a branch of your TIY-Assignments repo called feature/03--method-to-the-madness
switch to the new branch
Create at least one file and directory as described above in Deliverables.
Add and commit your work every hour or at every breakthrough (whichever comes first)
Push your commits to Github
In Github, open a PR from feature/03--method-to-the-madness into master
End of day wiki edit (please do these as your final tasks)
Add your thoughts on this assignment to the Assignment Evaluation page.
Update Light Bulbs and Things I Don't Get Yet to reflect how you feel at the end of the day.

**Comment by bgates** [comment]
Summon assistance on Pull Requests if you're unsure how to make one.

**Comment by malkin28025** [comment]
Our train just hit a car!!! Happy Monday!!!
