### ISSUE TITLE
03.5 -- Blackjack in Words -- Jeff Winkler

### ISSUE THREAD

**Issue by palmbeachjeff** [TheIronYard--Orlando/ROR--2015--SPRING#37]
* [x] Update Assignment Evaluation, Light Bulbs, Things I still don't get  
* [x] Post Wiki to Assignment below
* [x] Go through Blackjack commands in English
* [x] Post assignment in TIY-Assignments

**Comment by palmbeachjeff** [comment]
https://github.com/palmbeachjeff/TIY-Assignments/wiki

**Comment by palmbeachjeff** [comment]
https://github.com/palmbeachjeff/TIY-Assignments/wiki/Steps-to-create-a-Blackjack-game

**Comment by palmbeachjeff** [comment]
https://github.com/palmbeachjeff/TIY-Assignments/pull/3

**Comment by bgates** [comment]
That's a decent breakdown of the steps in blackjack. If you can keep that level of detail as you stare at problems, and improve your Ruby, you'll be fine.
