### ISSUE TITLE
04--Blackjack in Words - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#39]
Tasks

- [x] Update your TIY-Assignments wiki (M)
- [x] Create a branch in your TIY-Assignments repo, named appropriately (M)
    - [x] Study up on the game of blackjack (M)
    - [x] Include a code/ folder to add nouns and verbs. (S)
    - [ ] Create basic game to play one hand. (XL)
- [x] Open a Pull Request (PR) from your topic branch to master(S)
- [x] Add a link to your WIP Issue in a comment on your Pull Request(S)
- [ ] Comments on your WIP Issue as on previous assignments (S)
- [x] Link to your wiki (absolute URL) in WIP issue (S)
- [x] Link to your PR using Github Flavored Markdown  in WIP issue (S)

**Comment by QueVee** [comment]
Wiki Page
https://github.com/QueVee/TIY-Assignments/wiki

**Comment by bgates** [comment]
That's a very solid, concise description of what's involved in blackjack.

**Comment by bgates** [comment]
And such a clean PR!
