### ISSUE TITLE
00 -- It Begins -- Joe Cursi

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#4]

**Comment by bgates** [comment]
I see that the other repositories *exist*, but only if I go to your account page myself....

**Comment by malkin28025** [comment]
I resubmitted. Please let me know if it is incorrect.

**Comment by bgates** [comment]
I was referring to the two lines that had instructions like "Add a link to your new Github repo as a comment in your WIP Issue."

**Comment by malkin28025** [comment]
https://github.com/malkin28025/hello-world

**Comment by malkin28025** [comment]
https://github.com/malkin28025/TIY-Assignments-pt-2
